package g729

import (
	"errors"

	"github.com/exedev/g729/internal/acelp"
	"github.com/exedev/g729/internal/filter"
	"github.com/exedev/g729/internal/lpc"
	"github.com/exedev/g729/internal/lsp"
	"github.com/exedev/g729/internal/pcm"
	"github.com/exedev/g729/internal/pitch/openloop"
)

// Encoder holds G.729 Annex A encoder state for one logical stream.
//
// All buffers are preallocated; EncodeFrame allocates 0 in steady state.
// Concurrent calls on the same Encoder are a data race; callers needing
// parallel encoding must own one Encoder per channel.
type Encoder struct {
	pre pcm.PreProcessor

	// §5.3 preallocated histories.
	oldSpeech  [240]int16
	oldWspeech [143]int16
	oldExc     [154]int16
	synMem     [10]int16
	wMem       [10]int16
	errMem     [10]int16
	lspOld     [10]int16
	lspOldQ    [10]int16
	pastQuaEn  [4]int16
	freqPrev   [4][10]int16

	// FIX-3-B (Phase 2a INT-1 d10): count of frames that triggered the
	// anti-palindromic LP guard in lpcStep (LPToLSP returned
	// ErrLPCNonStable → previous-frame LSP reuse). Diagnostic-only;
	// not gating. Per spec §3.2.6 stability-and-reuse precedent.
	lspReuseCount uint64

	// Phase 2b INT-0: open-loop pitch state.
	//
	// aQ12Latest caches the order-10 LP polynomial (Q12) produced by
	// the most recent lpcStep call so openloopStep can build A(z/γ)
	// and A'(z) per §A.3.3 without re-running LP analysis. Phase 2b
	// stand-in for Â — the quantized-LP reconstruction is OQ-2 work
	// (Phase 2b plan §1 line 42).
	//
	// lpResidualMem and swMem are the §A.3.3 filter memories owned
	// by the encoder per the I10 / Phase-2a state-isolation
	// doctrine: the openloop package's helpers are pure on these
	// pointers and the root encoder coordinates lifetime.
	//
	// tOp records the most recently computed open-loop pitch
	// T_op ∈ [20,143] so Phase 2c (closed-loop refinement) can
	// recover the search centre without re-running §A.3.4.
	aQ12Latest    [lpc.LPCOrder + 1]int16
	lpResidualMem [10]int16
	swMem         [10]int16
	tOp           int16

	// Per-block state owners.
	lpc    lpc.Analyzer
	acelp  acelp.Searcher
	weight filter.Weighting
}

// NewEncoder returns an Encoder in initial state.
func NewEncoder() *Encoder {
	e := &Encoder{}
	lsp.InitFreqPrev(&e.freqPrev)
	lsp.InitLSPOld(&e.lspOld)
	return e
}

// Reset returns the Encoder to initial state. Equivalent to using a fresh
// NewEncoder, but reuses the existing memory.
func (e *Encoder) Reset() {
	*e = Encoder{}
	lsp.InitFreqPrev(&e.freqPrev)
	lsp.InitLSPOld(&e.lspOld)
}

// LSPReuseCount returns the running tally of frames where the
// FIX-3-B anti-palindromic LP guard fired (LPToLSP returned
// ErrLPCNonStable → previous-frame LSP reuse). Diagnostic-only;
// not part of the encoded bitstream. See §3.2.6 / §3.2.3 cite in
// lpcStep.
func (e *Encoder) LSPReuseCount() uint64 { return e.lspReuseCount }

// EncodeFrame consumes exactly FrameSamples samples and writes exactly
// FrameBytes bytes to out. Internal state is retained across calls.
//
// Phase 2-0 stub: validates lengths and returns ErrNotImplemented. Real
// encoding is wired in Phase 2a..2f. Phase 2a wires only the
// LP-analysis + LSP-quantization sub-chain via the package-private
// lpcStep helper; the public EncodeFrame remains a stub until later
// phases land the pitch / FCB / gain / packing pipeline.
func (e *Encoder) EncodeFrame(pcm []int16, out []byte) error {
	if len(pcm) != FrameSamples {
		return ErrShortPCM
	}
	if len(out) < FrameBytes {
		return ErrShortOutput
	}
	return ErrNotImplemented
}

// lpcStep runs the §3.2.1–§3.2.4 chain on one 80-sample PCM frame
// and returns the LSP quantizer indices (L0, L1, L2, L3) for that
// frame. Internal state advanced per call:
//
//	e.oldSpeech : 240-sample sliding analysis buffer (shifted left by
//	              80 each call; new pre-processed samples appended at
//	              [160..239]).
//	e.freqPrev  : MA-predictor FIFO; commitPredictorMemory advances
//	              it once Quantize selects the L0 winner.
//
// Buffer-shift convention (per plan §3.2.1 cite line 671). The
// 30 ms LP analysis window covers 240 = 200 past + 40 future
// samples. With the slide-by-80 layout used here the window applied
// at iteration n centres on oldSpeech[200], so the analysis output
// at iteration n corresponds to the speech segment ending at the
// first 40 samples of frame n — i.e. there is a 1-frame
// analysis-vs-encode delay between PCM-in and indices-out. Phase 2a
// gate vector LSP.BIT was generated by ITU's encoder under this
// convention; Phase 2b will own the same shift ordering for the
// pitch / FCB stages.
//
// I3 / I4: pure (apart from advancing e.oldSpeech / e.freqPrev),
// zero allocation; all per-frame scratch lives in stack arrays.
func (e *Encoder) lpcStep(pcm []int16) (lsp.Indices, error) {
	if len(pcm) != FrameSamples {
		return lsp.Indices{}, ErrShortPCM
	}

	var processed [FrameSamples]int16
	e.pre.Process(pcm, processed[:])

	copy(e.oldSpeech[0:160], e.oldSpeech[80:240])
	copy(e.oldSpeech[160:240], processed[:])

	var aQ12 [lpc.LPCOrder + 1]int16
	if err := e.lpc.Analyze(&e.oldSpeech, &aQ12); err != nil {
		return lsp.Indices{}, err
	}
	e.aQ12Latest = aQ12

	var qQ15 [10]int16
	if err := lsp.LPToLSP(&aQ12, &qQ15); err != nil {
		// FIX-3-B (Phase 2a INT-1 d10): anti-palindromic LP guard.
		//
		// Spec citation: G.729 (06/2012) §3.2.3 establishes the F1/F2
		// sum/difference polynomial construction and the 60-point
		// sign-change scan, but is silent on the degenerate case
		// where a[k] = ±a[10−k] makes one polynomial identically
		// zero (no sign changes ⇒ root extraction fails). §3.2.6
		// (LSP→LP for the synthesis filter) provides the
		// stability-and-reuse precedent: when a freshly reconstructed
		// LSP vector violates the ordering / spacing constraints,
		// the previous frame's quantized LSPs are reused. Applying
		// the same precedent here keeps the encoder graceful on
		// rare anti-palindromic transients (e.g. LSP.IN frame 596)
		// instead of fail-fast at the first non-stable frame.
		//
		// Cold-start safety: NewEncoder / Reset seed e.lspOld via
		// InitLSPOld (cos(i·π/11) Q15 per §3.2.6 / §4.1.5), so the
		// fallback is well-defined even if the very first frame
		// triggers the guard.
		if errors.Is(err, lsp.ErrLPCNonStable) {
			qQ15 = e.lspOld
			e.lspReuseCount++
		} else {
			return lsp.Indices{}, err
		}
	} else {
		// Successful extraction: cache for future-frame reuse.
		e.lspOld = qQ15
	}

	var omega [10]int16
	lsp.LSPToLSF(&qQ15, &omega)

	return lsp.Quantize(&omega, &e.freqPrev), nil
}

// openloopStep runs the §A.3.3 weighted-speech construction and the
// §A.3.4 open-loop pitch search on the most recently analyzed frame.
// It must be called after lpcStep on the same frame: lpcStep populates
// e.aQ12Latest and writes the pre-processed PCM into e.oldSpeech[160:240],
// both of which openloopStep consumes.
//
// State advanced per call:
//
//	e.lpResidualMem : 10-sample s-history for eq. A.3
//	e.swMem         : 10-sample sw-history for eq. A.2
//	e.oldWspeech    : 143-sample sw history (slid in-place per
//	                  slideOldWspeech / I-2b-2)
//	e.tOp           : the per-frame open-loop pitch ∈ [20,143]
//
// I3 / I4: pure (apart from advancing the four state buffers above);
// zero allocation. The 80-sample current-frame view is taken via a
// pointer-to-array reslice over e.oldSpeech, avoiding a stack copy.
func (e *Encoder) openloopStep() int16 {
	s := (*[FrameSamples]int16)(e.oldSpeech[160:240])
	e.tOp = openloop.Step(&e.aQ12Latest, s, &e.lpResidualMem, &e.swMem, &e.oldWspeech)
	return e.tOp
}
