package g729

import (
	"github.com/exedev/g729/internal/acelp"
	"github.com/exedev/g729/internal/filter"
	"github.com/exedev/g729/internal/lpc"
	"github.com/exedev/g729/internal/lsp"
	"github.com/exedev/g729/internal/pcm"
)

// Encoder holds G.729 Annex A encoder state for one logical stream.
//
// All buffers are preallocated; EncodeFrame allocates 0 in steady state.
// Concurrent calls on the same Encoder are a data race; callers needing
// parallel encoding must own one Encoder per channel.
type Encoder struct {
	pre pcm.PreProcessor

	// §5.3 preallocated histories.
	oldSpeech  [240]int16
	oldWspeech [143]int16
	oldExc     [154]int16
	synMem     [10]int16
	wMem       [10]int16
	errMem     [10]int16
	lspOld     [10]int16
	lspOldQ    [10]int16
	pastQuaEn  [4]int16
	freqPrev   [4][10]int16

	// Per-block state owners.
	lpc    lpc.Analyzer
	acelp  acelp.Searcher
	weight filter.Weighting
}

// NewEncoder returns an Encoder in initial state.
func NewEncoder() *Encoder {
	e := &Encoder{}
	lsp.InitFreqPrev(&e.freqPrev)
	return e
}

// Reset returns the Encoder to initial state. Equivalent to using a fresh
// NewEncoder, but reuses the existing memory.
func (e *Encoder) Reset() {
	*e = Encoder{}
	lsp.InitFreqPrev(&e.freqPrev)
}

// EncodeFrame consumes exactly FrameSamples samples and writes exactly
// FrameBytes bytes to out. Internal state is retained across calls.
//
// Phase 2-0 stub: validates lengths and returns ErrNotImplemented. Real
// encoding is wired in Phase 2a..2f. Phase 2a wires only the
// LP-analysis + LSP-quantization sub-chain via the package-private
// lpcStep helper; the public EncodeFrame remains a stub until later
// phases land the pitch / FCB / gain / packing pipeline.
func (e *Encoder) EncodeFrame(pcm []int16, out []byte) error {
	if len(pcm) != FrameSamples {
		return ErrShortPCM
	}
	if len(out) < FrameBytes {
		return ErrShortOutput
	}
	return ErrNotImplemented
}

// lpcStep runs the §3.2.1–§3.2.4 chain on one 80-sample PCM frame
// and returns the LSP quantizer indices (L0, L1, L2, L3) for that
// frame. Internal state advanced per call:
//
//	e.oldSpeech : 240-sample sliding analysis buffer (shifted left by
//	              80 each call; new pre-processed samples appended at
//	              [160..239]).
//	e.freqPrev  : MA-predictor FIFO; commitPredictorMemory advances
//	              it once Quantize selects the L0 winner.
//
// Buffer-shift convention (per plan §3.2.1 cite line 671). The
// 30 ms LP analysis window covers 240 = 200 past + 40 future
// samples. With the slide-by-80 layout used here the window applied
// at iteration n centres on oldSpeech[200], so the analysis output
// at iteration n corresponds to the speech segment ending at the
// first 40 samples of frame n — i.e. there is a 1-frame
// analysis-vs-encode delay between PCM-in and indices-out. Phase 2a
// gate vector LSP.BIT was generated by ITU's encoder under this
// convention; Phase 2b will own the same shift ordering for the
// pitch / FCB stages.
//
// I3 / I4: pure (apart from advancing e.oldSpeech / e.freqPrev),
// zero allocation; all per-frame scratch lives in stack arrays.
func (e *Encoder) lpcStep(pcm []int16) (lsp.Indices, error) {
	if len(pcm) != FrameSamples {
		return lsp.Indices{}, ErrShortPCM
	}

	var processed [FrameSamples]int16
	e.pre.Process(pcm, processed[:])

	copy(e.oldSpeech[0:160], e.oldSpeech[80:240])
	copy(e.oldSpeech[160:240], processed[:])

	var aQ12 [lpc.LPCOrder + 1]int16
	if err := e.lpc.Analyze(&e.oldSpeech, &aQ12); err != nil {
		return lsp.Indices{}, err
	}

	var qQ15 [10]int16
	if err := lsp.LPToLSP(&aQ12, &qQ15); err != nil {
		return lsp.Indices{}, err
	}

	var omega [10]int16
	lsp.LSPToLSF(&qQ15, &omega)

	return lsp.Quantize(&omega, &e.freqPrev), nil
}
